version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    # volumes:
    #   - postgres:/var/lib/postgresql/data

volumes:
  database:
    driver: local


networks:
  default: